"""Seed the CBSE Class 12 Biology worksheet (Sexual Reproduction in Flowering
Plants & Human Reproduction) — 75 MCQs, with diagram images for figure-based
questions. Idempotent: uses deterministic ids so re-running updates in place."""
import os, json, uuid
from biology_tables import restore_table
from datetime import datetime, timezone

_NS = uuid.uuid5(uuid.NAMESPACE_DNS, "cbse-bio-ws.examnest.io")
SOURCE_TAG = "cbse_bio_ws"
TEST_ID = str(uuid.uuid5(_NS, "test"))
CHAPTER = "Sexual Reproduction in Flowering Plants & Human Reproduction"

_IMG_PATH = os.path.join(os.path.dirname(__file__), "bio_images.json")
try:
    with open(_IMG_PATH) as _f:
        IMAGES = json.load(_f)   # {"12": "data:image/png;base64,...", ...}
except Exception:
    IMAGES = {}


def _now():
    return datetime.now(timezone.utc).isoformat()


def _qid(n):
    return str(uuid.uuid5(_NS, f"q{n}"))


# Per-question difficulty (easy = direct recall, medium = conceptual, hard = diagram/multi-statement)
DIFFICULTY = {
 1: "easy", 2: "medium", 3: "medium", 4: "easy", 5: "medium", 6: "medium", 7: "medium",
 8: "medium", 9: "easy", 10: "medium", 11: "hard", 12: "hard", 13: "easy", 14: "hard",
 15: "easy", 16: "easy", 17: "easy", 18: "hard", 19: "hard", 20: "medium", 21: "medium",
 22: "hard", 23: "hard", 24: "hard", 25: "medium", 26: "hard", 27: "hard", 28: "hard",
 29: "medium", 30: "hard", 31: "hard", 32: "medium", 33: "hard", 34: "easy", 35: "medium",
 36: "medium", 37: "hard", 38: "hard", 39: "easy", 40: "medium", 41: "medium", 42: "easy",
 43: "easy", 44: "easy", 45: "easy", 46: "easy", 47: "medium", 48: "hard", 49: "medium",
 50: "hard", 51: "medium", 52: "hard", 53: "medium", 54: "medium", 55: "medium", 56: "hard",
 57: "easy", 58: "hard", 59: "medium", 60: "hard", 61: "easy", 62: "hard", 63: "medium",
 64: "hard", 65: "medium", 66: "medium", 67: "medium", 68: "medium", 69: "medium", 70: "hard",
 71: "hard", 72: "hard", 73: "easy", 74: "medium", 75: "medium",
}


# (number, question_text, [options], correct_letter, explanation)
QUESTIONS = [
 (1, "The type of pollination involving transfer of pollen grains from anther to the stigma of the same flower is known as:",
  ["Xenogamy", "Apogamy", "Autogamy", "Geitonogamy"], "C",
  "Autogamy is self-pollination within the same flower."),
 (2, "After spermiogenesis, the sperm heads get embedded in which of the following cells?",
  ["Seminal vesicle", "Sertoli cells", "Germinal epithelium", "Leydig cells"], "B",
  "Sperm heads become embedded in Sertoli cells, which nourish them."),
 (3, "In the human female, menstruation can be deferred by the administration of:",
  ["Combination of FSH and LH", "FSH only", "Combination of estrogens and progesterone", "LH only"], "C",
  "Estrogen + progesterone maintain the endometrium and defer menstruation."),
 (4, "The period between fertilization and birth is called ______.",
  ["Parturition", "Ovulation", "Gestation", "Germination"], "C",
  "Gestation is the pregnancy period between fertilization and birth."),
 (5, "Number of secondary spermatocytes required to produce 200 spermatozoa are:",
  ["100", "50", "200", "400"], "A",
  "Each secondary spermatocyte forms 2 spermatids → 2 sperm, so 100 give 200."),
 (6, "Menstrual cycle occurs due to lack of:",
  ["Oxytocin", "FSH", "Vasopressin", "Progesterone"], "D",
  "Fall in progesterone (after corpus luteum degenerates) triggers menstruation."),
 (7, "In human female, the blastocyst",
  ["Gets nutrition from uterine endometrial secretion only after implantation.",
   "Gets implanted in endometrium by trophoblast cells.",
   "Gets implanted into uterus three days after ovulation.",
   "Forms placenta even before implantation."], "B",
  "Trophoblast cells of the blastocyst implant it into the endometrium."),
 (8, "Which of the following depicts the correct pathway of transport of sperms?",
  ["Rete testis → Vas deferens → Efferent ductules → Epididymis",
   "Rete testis → Epididymis → Efferent ductules → Vas deferens",
   "Rete testis → Efferent ductules → Epididymis → Vas deferens",
   "Efferent ductules → Rete testis → Vas deferens → Epididymis"], "C",
  "Rete testis → efferent ductules → epididymis → vas deferens."),
 (9, "Two hormones that regulate the menstrual cycle are:",
  ["FSH and estrogen", "Estrogens and ostrogen", "Estrogens and progesterone", "FSH and ostrogen"], "C",
  "Estrogen and progesterone are the ovarian hormones regulating the cycle."),
 (10, "The membranous cover of the ovum at ovulation is:",
  ["Chorion", "Zona pellucida", "Corona radiata", "Zona radiata"], "B",
  "The zona pellucida is the glycoprotein membranous cover of the ovum."),
 (11, "If mammalian ovum fails to get fertilized, which one of the following is unlikely?",
  ["Estrogen secretion further decreases", "Corpus luteum will degenerate",
   "Primary follicle starts developing", "Progesterone secretion rapidly declines"], "A",
  "CL degenerates and progesterone falls; a further decrease in estrogen is unlikely."),
 (12, "Identify the human developmental stage shown below as well as the related right place of its occurrence in a normal pregnant woman and select the right option for the two, together:",
  ["Option d is correct.", "Option a is correct.", "Option c is correct.", "Option b is correct."], "C",
  "The blastocyst gets implanted in the uterine wall (row c)."),
 (13, "After ovulation the structure formed by the rupture of follicle is known as:",
  ["Corpus mammilare", "Corpus albicans", "Corpus callosum", "Corpus luteum"], "D",
  "The ruptured Graafian follicle forms the corpus luteum."),
 (14, "In a normal pregnant woman, the amount of total gonadotropin activity was assessed. The result expected was",
  ["High level of circulating FSH and LH in the uterus to stimulate implantation of the embryo.",
   "High level of circulating hCG to stimulate estrogen and progesterone synthesis.",
   "High level of FSH and LH in uterus to stimulate endometrial thickening.",
   "High level of circulating hCG to stimulate endometrial thickening."], "B",
  "hCG maintains the corpus luteum, stimulating estrogen and progesterone."),
 (15, "The enlarged end of penis, called glans penis, is covered by a loose skin fold called:",
  ["Perimetrium", "Infundibulum", "Prepuce", "Myometrium"], "C",
  "The prepuce (foreskin) is the loose skin fold over the glans penis."),
 (16, "Which one is called the pregnancy hormone:",
  ["Progesterone", "Estrogen", "Testosterone", "Oxytocin"], "A",
  "Progesterone maintains pregnancy and is called the pregnancy hormone."),
 (17, "Human sperm moves by:",
  ["Nucleosome", "Basal body", "Flagellum", "Cilia"], "C",
  "The sperm tail is a flagellum enabling motility."),
 (18, "In the given diagram name the parts A, B, C, D and E",
  ["A - germ pore, B - Generative cell, C - exine, D - entine, E - vegetative cell",
   "A - intine, B - exine, C - germ pore, D - Generative cell, E - vegetative cell",
   "A - germ pore, B - Generative cell, C - intine, D - exine, E - vegetative cell",
   "A - exine, B - intine, C - Generative cell, D - germ pore, E - vegetative cell"], "C",
  "A germ pore, generative cell, intine, exine and vegetative cell."),
 (19, "Select the option that correctly matches with the labelling in the given diagram of T.S. of an apple which categorizes it as a false fruit.",
  ["P - Thalamus", "S - Mesocarp", "R - Endocarp", "Q - Seed"], "A",
  "In apple the fleshy edible part (P) develops from the thalamus — a false fruit."),
 (20, "Choose the correct option in which the diagram of the flowering plant shown below is correctly matched with the drug obtained from it:",
  ["Datura - Depressant", "Datura - Hallucinogen", "Cannabis - Stimulant", "Poppy - Depressant"], "B",
  "The plant is Datura, source of a hallucinogen."),
 (21, "Which kind of embryo is shown in the figure below",
  ["Heart shaped embryo", "Globular embryo", "Mature embryo", "Pre-embryo"], "A",
  "The two-lobed apex indicates a heart-shaped embryo stage."),
 (22, "The diagram below shows a fertilised ovule and carpel. Which numbers represent the structures which will become (i) the future embryo, (ii) the future testa, (iii) the future micropyle of the seeds",
  ["(i) - (6), (ii) - (3), (iii) - (7)", "(i) - (5), (ii) - (2), (iii) - (4)",
   "(i) - (5), (ii) - (3), (iii) - (1)", "(i) - (7), (ii) - (8), (iii) - (4)"], "B",
  "Egg/zygote (5) → embryo, integument (2) → testa, opening (4) → micropyle."),
 (23, "In the diagram given, parts labelled as 'A', 'B', 'C', 'D', 'E' and 'F' are respectively identified as:",
  ["Synergids, polar nuclei, central cell, antipodals, filiform apparatus and egg.",
   "Central cell, polar nuclei, filiform apparatus, antipodals, synergids and egg.",
   "Polar nuclei, egg, antipodals, central cell, filiform apparatus and synergids.",
   "Egg, synergids, central cell, filiform apparatus, antipodals and polar nuclei."], "A",
  "D (top) = antipodals, B = polar nuclei, C = central cell, with egg apparatus below."),
 (24, "The figure below shows a typical embryo, name the part (1), (2) and (3) respectively",
  ["Cotyledons, Plumule and suspensor", "Plumule, cotyledons and suspensor",
   "Suspensor, Plumule and cotyledons", "Plumule, suspensor and cotyledons"], "B",
  "(1) plumule, (2) cotyledons, (3) lower axis/suspensor end."),
 (25, "Select the correct order of endosperm types:",
  ["Cellular, helobial, free nuclear", "Free nuclear, cellular, helobial",
   "Cellular, free nuclear, helobial", "Helobial, free nuclear, cellular"], "B",
  "The three endosperm types are free-nuclear, cellular and helobial."),
 (26, "The figure given below depicts a diagrammatic sectional view of female reproductive system of humans. Which one of three parts out of I to VI have been correctly identified?",
  ["(II) Endometrium, (III) Infundibulum, (IV) Fimbriae",
   "(III) Infundibulum, (IV) Fimbriae, (V) Cervix",
   "(IV) Oviducal funnel, (V) Uterus, (VI) Cervix",
   "(I) Perimetrium, (II) Myometrium, (III) Fallopian tube"], "B",
  "III infundibulum, IV fimbriae and V cervix are correctly identified."),
 (27, "Choose the correct option with right labellings of following figure:",
  ["A = cervix, B = uterus, C = oviduct, D = ovary",
   "A = cervix, B = uterus, C = ovary, D = oviduct",
   "A = uterus, B = cervix, C = oviduct, D = ovary",
   "A = oviduct, B = uterus, C = cervix, D = ovary"], "A",
  "A cervix, B uterus, C oviduct, D ovary."),
 (28, "In the sectional view of the female reproductive system, Label (III) and (IV).",
  ["uterus, ovary respectively", "fimbriae, endometrium respectively",
   "infundibulum, perimetrium respectively", "infundibulum, fimbriae respectively"], "D",
  "III is the infundibulum (funnel) and IV the fimbriae."),
 (29, "Observe the following line diagram depicting the 28 days menstrual cycle of a healthy young woman. Select the option of days on which this woman would be most and least fertile.",
  ["Most fertile days: 1-7 Least fertile days: 14-21",
   "Most fertile days: 10-17 Least fertile days: 21-28",
   "Most fertile days: 14-21 Least fertile days: 1-7",
   "Most fertile days: 21-28 Least fertile days: 7-14"], "B",
  "Fertility peaks around ovulation (day 14); least fertile far from it (21-28)."),
 (30, "Choose the correct combination of labelling the hormonal control of female reproductive system",
  ["(a) - GnRH, (b) - LH/FSH, (c) - oestrogen or progesterone, (d) - uterus",
   "(a) - GnRH, (b) - STH, (c) - LH, (d) - uterus",
   "(a) - GnRH, (b) - TH, (c) - LTH, (d) - uterus",
   "(a) - GnRH, (b) - ACTH, (c) - LH, (d) - uterus"], "A",
  "Hypothalamus→GnRH, pituitary→LH/FSH, ovary→estrogen/progesterone acting on uterus."),
 (31, "Match the correct Structures given in Column I with the Fruit in Column II: P. Perisperm; Q. Thalamus; R. Pericarp; S. Endosperm — (i) Maize, (ii) Black pepper, (iii) Strawberry, (iv) Mango",
  ["P - i, Q - ii, R - iii, S - ii", "P - iv, Q - i, R - ii, S - iv",
   "P - iii, Q - i, R - i, S - iii", "P - ii, Q - iii, R - iv, S - i"], "D",
  "Perisperm-black pepper, thalamus-strawberry, pericarp-mango, endosperm-maize."),
 (32, "Match column I with II: (a) Funicle, (b) Integuments, (c) Chalaza, (d) Hilum, (e) Micropyle — (i) Small opening of ovule, (ii) Stalk of ovule, (iii) Protective envelopes, (iv) Junction of ovule and stalk, (v) Basal part of ovule",
  ["(a)-(i), (b)-(iii), (c)-(ii), (d)-(iv), (e)-(v)",
   "(a)-(ii), (b)-(iii), (c)-(v), (d)-(iv), (e)-(i)",
   "(a)-(ii), (b)-(iii), (c)-(i), (d)-(iv), (e)-(v)",
   "(a)-(ii), (b)-(iv), (c)-(v), (d)-(i), (e)-(iii)"], "B",
  "Funicle-stalk, integuments-envelopes, chalaza-basal, hilum-junction, micropyle-opening."),
 (33, "Match ovular structure with post-fertilization structure: (a) Ovule, (b) Funiculus, (c) Nucellus, (d) Polar nuclei — (i) Endosperm, (ii) Aril, (iii) Seed, (iv) Perisperm",
  ["(a)-(iii), (b)-(ii), (c)-(iv), (d)-(i)", "(a)-(ii), (b)-(iii), (c)-(i), (d)-(iv)",
   "(a)-(iii), (b)-(ii), (c)-(i), (d)-(iv)", "(a)-(ii), (b)-(iii), (c)-(iv), (d)-(i)"], "A",
  "Ovule-seed, funiculus-aril, nucellus-perisperm, polar nuclei-endosperm."),
 (34, "Match parts of the sperm with functions: (a) Head, (b) Middle piece, (c) Acrosome, (d) Tail — (i) Enzymes, (ii) Sperm motility, (iii) Energy, (iv) Genetic material",
  ["(a)-(iv), (b)-(iii), (c)-(i), (d)-(ii)", "(a)-(iv), (b)-(i), (c)-(ii), (d)-(iii)",
   "(a)-(ii), (b)-(i), (c)-(iii), (d)-(iv)", "(a)-(ii), (b)-(iv), (c)-(i), (d)-(iii)"], "A",
  "Head-genetic material, middle piece-energy, acrosome-enzymes, tail-motility."),
 (35, "Match the following: (a) Trophoblast, (b) Cleavage, (c) Inner cell mass, (d) Implantation — (i) Embedding of blastocyst in endometrium, (ii) Group of cells that differentiate as embryo, (iii) Outer layer of blastocyst attached to endometrium, (iv) Mitotic division of zygote",
  ["(a)-(ii), (b)-(i), (c)-(iii), (d)-(iv)", "(a)-(iii), (b)-(i), (c)-(ii), (d)-(iv)",
   "(a)-(ii), (b)-(iv), (c)-(iii), (d)-(i)", "(a)-(iii), (b)-(iv), (c)-(ii), (d)-(i)"], "D",
  "Trophoblast-outer layer, cleavage-mitosis, ICM-embryo, implantation-embedding."),
 (36, "Match column-I with column-II: (a) Proliferative phase, (b) Secretory phase, (c) Menstruation — (i) Breakdown of endometrial lining, (ii) Follicular phase, (iii) Luteal phase",
  ["(a) - (ii), (b) - (iii), (c) - (ii)", "(a) - (iii), (b) - (ii), (c) - (i)",
   "(a) - (ii), (b) - (iii), (c) - (i)", "(a) - (iii), (b) - (i), (c) - (ii)"], "C",
  "Proliferative=follicular, secretory=luteal, menstruation=breakdown of lining."),
 (37, "Match column-I with column-II: (a) Mons pubis, (b) Antrum, (c) Trophoectoderm, (d) Nebenkern — (i) Embryo formation, (ii) Sperm, (iii) Female external genitalia, (iv) Graafian follicle",
  ["(a) - (iii), (b) - (iv), (c) - (ii), (d) - (i)",
   "(a) - (i), (b) - (iv), (c) - (iii), (d) - (ii)",
   "(a) - (iii), (b) - (i), (c) - (iv), (d) - (ii)",
   "(a) - (iii), (b) - (iv), (c) - (i), (d) - (ii)"], "D",
  "Mons pubis-external genitalia, antrum-Graafian follicle, trophoectoderm-embryo, nebenkern-sperm."),
 (38, "Which option correctly matches the hormone to its site of production? P. Oxytocin; Q. Relaxin; R. hCG; S. Progesterone — (i) Placenta, (ii) Corpus Luteum, (iii) Pituitary Gland, (iv) Ovaries",
  ["P - i, Q - iii, R - ii, S - iv", "P - i, Q - iv, R - iii, S - ii",
   "P - ii, Q - iii, R - i, S - iv", "P - iii, Q - iv, R - i, S - ii"], "D",
  "Oxytocin-pituitary, relaxin-ovaries, hCG-placenta, progesterone-corpus luteum."),
 (39, "Megaspore mother cell undergoes reduction division to form ______ megaspores.",
  ["Four", "Three", "One", "Two"], "A",
  "Meiosis of the megaspore mother cell produces four haploid megaspores."),
 (40, "Embryo sac is to ovule as ______ is to an anther.",
  ["Stamen", "Filament", "Pollen grain", "Androecium"], "C",
  "The pollen grain (male gametophyte) is contained within the anther."),
 (41, "Pollen grain develops from ______ of anther.",
  ["Epidermis", "Endothecium", "Sporogenous tissue", "Middle layer"], "C",
  "Sporogenous tissue gives rise to microspore mother cells and pollen grains."),
 (42, "The anther is a four-sided structure consisting of four ______ located at the corner.",
  ["Macrosporangia", "Megasporangia", "Minisporangia", "Microsporangia"], "D",
  "A typical anther is tetrasporangiate with four microsporangia."),
 (43, "The wall of the uterus has ______ layers of tissues.",
  ["Four", "Three", "Two", "Five"], "B",
  "Perimetrium, myometrium and endometrium — three layers."),
 (44, "Ovulation occurs on the ______ day of the menstrual cycle.",
  ["Last", "08-10", "12-14", "14-16"], "C",
  "Ovulation occurs around day 14 of a 28-day cycle."),
 (45, "Mother's milk during initial days of lactation is rich in ______ antibodies.",
  ["IgA", "IgM", "IgG", "IgE"], "A",
  "Colostrum is rich in IgA antibodies giving passive immunity."),
 (46, "What is the correct sequence of sperm formation?",
  ["spermatogonia, spermatocyte, spermatozoa, spermatid",
   "spermatid, spermatocyte, spermatogonia, spermatozoa",
   "spermatogonia, spermatocyte, spermatid, spermatozoa",
   "spermatogonia, spermatozoa, spermatocyte, spermatid"], "C",
  "Spermatogonia → spermatocyte → spermatid → spermatozoa."),
 (47, "Which of the following statement is/are correct? I: Seed is the basis of agriculture. II: Dehydration and dormancy of mature seed are crucial for the storage of seeds. III: Seeds of rice and wheat remain viable for several years at normal conditions.",
  ["Statements I and III are correct", "Only statement III is correct",
   "Statements I and II are correct", "Statements II and III are correct"], "C",
  "I and II are correct; rice/wheat seeds are not viable for several years normally."),
 (48, "Which of the following statements are correct? I: Embryos of monocotyledons possess only one cotyledon. II: In the grass family the cotyledon is called scutellum. III: In monocot embryo radicle and root cap is covered by coleoptile.",
  ["All statements are correct.", "Statement I and II are correct only.",
   "Statement I and III are correct only.", "Statement II and III are correct only."], "B",
  "III is wrong — radicle/root cap are enclosed by the coleorhiza, not coleoptile."),
 (49, "Which of the following statements are correct? I: Megaspore mother cell undergoes meiotic division to form four megaspores. II: One of the megaspore degenerate and three remain functional. III: Only functional megaspore develops into the female gametophyte.",
  ["Statement I, II, and III are correct", "Statement I and II are correct",
   "Statement I and III are correct", "Statement I, II, and III are incorrect"], "C",
  "II is wrong — three megaspores degenerate and one remains functional."),
 (50, "Find out the wrong statement:",
  ["Amnion is outer layer containing amniotic fluid that acts as shock absorber to soft embryo.",
   "Yolk sac is a foetal membrane that helps in nourishment of the embryo.",
   "In mammals, allantois is not excretory in function.",
   "Chorio-allantoic membrane develops villi and participates in development of placenta."], "A",
  "Amnion is the inner membrane; the chorion is the outer membrane."),
 (51, "From the statements below choose the option that is/are true for a typical female gametophyte: i. It is 8-nucleate and 7-celled at maturity. ii. It is free-nuclear during development. iii. It is situated inside the integument but outside the nucellus. iv. It has an egg apparatus situated at the chalazal end.",
  ["i and ii", "ii and iii", "ii and iv", "i and iv"], "A",
  "It is 8-nucleate/7-celled and free-nuclear during development (i and ii)."),
 (52, "Which one of the following statements is wrong? (a) When pollen is shed at two-celled stage, double fertilization does not take place. (b) Vegetative cell is larger than generative cell. (c) Pollen grains in some plants remain viable for months. (d) Intine is made up of cellulose and pectin.",
  ["Statement (d) is incorrect.", "Statement (c) is incorrect.",
   "Statement (a) is incorrect.", "Statement (b) is incorrect."], "C",
  "Statement (a) is wrong — double fertilization still occurs."),
 (53, "Choose the correct statement from the following:",
  ["Chasmogamous flowers always exhibit geitonogamy.",
   "Cleistogamous flowers always exhibit autogamy.",
   "Cleistogamous flowers exhibit both autogamy and geitonogamy.",
   "Chasmogamous flowers never exhibit autogamy."], "B",
  "Cleistogamous flowers do not open, so they are invariably autogamous."),
 (54, "Which of the following statements about sporopollenin is false? (a) Exine is made up of sporopollenin. (b) Sporopollenin is one of the resistant organic materials. (c) Exine has apertures called germ pores where sporopollenin is present. (d) Sporopollenin can withstand high temperatures and strong acids.",
  ["Statement a is false.", "Statement d is false.",
   "Statement b is false.", "Statement c is false."], "D",
  "Germ pores are regions where sporopollenin is ABSENT, so (c) is false."),
 (55, "Which one of the following statements is not true? (a) Tapetum helps in the dehiscence of anther. (b) Exine of pollen grains is made up of sporopollenin. (c) Pollen grains of many species cause severe allergies. (d) Stored pollen in liquid nitrogen can be used in crop breeding programmes.",
  ["Statement (d) is incorrect.", "Statement (a) is incorrect.",
   "Statement (c) is incorrect.", "Statement (b) is incorrect."], "B",
  "Dehiscence is aided by the endothecium; the tapetum nourishes — (a) is not true."),
 (56, "Which of the following statements is not correct? (a) Pollen grains of many species can germinate on the stigma but only one pollen tube of the same spore grows into the style. (b) Insects that consume pollen/nectar without pollination are pollen/nectar robbers. (c) Pollen germination and tube growth are regulated by chemical components of pollen and pistil. (d) Some reptiles have also been reported as pollinators.",
  ["Statement (c) is incorrect.", "Statement (d) is incorrect.",
   "Statement (a) is incorrect.", "Statement (b) is incorrect."], "C",
  "Statement (a) is not correct — many pollen tubes grow into the style."),
 (57, "Which of the following are haploid in nature? 1. Spermatids 2. Secondary spermatocytes 3. Spermatogonia 4. Primary spermatocytes",
  ["2 and 4 are correct", "1 and 3 are correct", "1 and 2 are correct", "1, 2, 3 are correct"], "C",
  "Spermatids and secondary spermatocytes are haploid; spermatogonia and primary spermatocytes are diploid."),
 (58, "Which of the following is correct grouping? (a) Ectoderm - Retina, epidermis and nervous system (b) Mesoderm - Kidneys, connective tissue and testis (c) Mesoderm - Ovary, urinary bladder and kidneys (d) Endoderm - Thyroid, pineal and thymus",
  ["Option d is correct", "Option c is correct", "Option b is correct", "Option a is correct"], "D",
  "Retina, epidermis and nervous system are all ectodermal — grouping (a) is correct."),
 (59, "Cowper's glands secrete a substance to: 1. Nourish sperms 2. Neutralise the acidity 3. Kill pathogens 4. Lubricate female vagina to facilitate copulation",
  ["2 and 4 are correct", "1 and 2 are correct", "1, 2, 3 are correct", "1 and 3 are correct"], "A",
  "Bulbourethral (Cowper's) glands secrete lubricating mucus and help neutralise acidity."),
 (60, "Identify the correct statement from the following:",
  ["Oogonial cells start to proliferate and give rise to functional ova in regular cycles from puberty onwards.",
   "High levels of estrogen triggers the ovulatory surge.",
   "Progesterone level is high during the post ovulatory phase of menstrual cycle.",
   "Sperms released from seminiferous tubules are highly motile."], "C",
  "Progesterone (from the corpus luteum) is high in the post-ovulatory/luteal phase."),
 (61, "Which one of the following statements about the human male reproductive system is wrong?",
  ["Testosterone is synthesized and secreted by Leydig cells.",
   "The primary sex organ in human males is the ovary.",
   "Scrotum maintains a low temperature for spermatogenesis.",
   "Leydig cells are located in between the seminiferous tubules."], "B",
  "The primary sex organ in males is the testis, not the ovary."),
 (62, "Which one of the following statements about morula in humans is correct? (a) It has almost equal cytoplasm as an uncleaved zygote but much more DNA. (b) It has less cytoplasm as well as less DNA than an uncleaved zygote. (c) It has more or less equal quantity of cytoplasm and DNA as an uncleaved zygote. (d) It has more cytoplasm and more DNA than an uncleaved zygote.",
  ["Statement c is correct", "Statement b is correct", "Statement a is correct", "Statement d is correct"], "C",
  "Cleavage keeps cytoplasm ~constant but multiplies cells, so total DNA is much more — (a)."),
 (63, "Which of the following statements regarding the sperm is incorrect?",
  ["Mitochondria provide energy for the sperm.",
   "The head of sperm has nucleus capped by the acrosome.",
   "The acrosome is derived from the nucleus.",
   "The neck has proximal and distal centrioles."], "C",
  "The acrosome is derived from the Golgi apparatus, not the nucleus."),
 (64, "On the basis of nature of maternal and foetal tissues, the types of placentae are: i. Haemochorial placenta ii. Haemoendothelial placenta iii. Cotyledonary placenta iv. Deciduate placenta",
  ["2 and 4 are correct", "1 and 2 are correct", "1 and 3 are correct", "1, 2, 3 are correct"], "B",
  "Haemochorial and haemoendothelial types are classified by the tissues involved."),
 (65, "Which one of the following statements is incorrect about menstruation?",
  ["During normal menstruation about 40 ml blood is lost.",
   "At menopause in the female, there is especially abrupt increase in gonadotropic hormones.",
   "The menstrual fluid can easily clot.",
   "The beginning of the menstruation cycle is called menarche."], "C",
  "Menstrual fluid does not clot due to the presence of enzymes."),
 (66, "Select the incorrect statement: (a) LH triggers secretion of androgens from the Leydig cells. (b) FSH stimulates the Sertoli cells which help in spermiogenesis. (c) LH triggers ovulation in ovary. (d) LH and FSH decrease gradually during the follicular phase.",
  ["Statement c is incorrect", "Statement b is incorrect",
   "Statement a is incorrect", "Statement d is incorrect"], "D",
  "FSH and LH rise (not decrease) during the follicular phase — (d) is incorrect."),
 (67, "Identify the correct statement on inhibin: (a) Is produced by nurse cells in testes and inhibits secretion of LH. (b) Inhibits the secretion of LH, FSH and Prolactin. (c) Is produced by granulosa cells in ovary and inhibits secretion of FSH. (d) Is produced by granulosa cells in ovary and inhibits secretion of LH.",
  ["Statement d is correct", "Statement a is correct",
   "Statement b is correct", "Statement c is correct"], "D",
  "Inhibin from granulosa cells (and Sertoli cells) inhibits FSH — (c)."),
 (68, "Identify the false statement out of the following.",
  ["The menstrual cycle ceases during pregnancy.",
   "Leydig cells synthesize androgens.",
   "Androgens are produced by Sertoli cells.",
   "Spermatozoa get nutrition from Sertoli cells."], "C",
  "Androgens are produced by Leydig cells, not Sertoli cells."),
 (69, "The spermatogonia undergo division to produce sperms by spermatogenesis. Choose the correct statement.",
  ["Spermatogonia have 46 chromosomes and always undergoes meiotic cell division.",
   "Secondary spermatocytes have 23 chromosomes and undergo second meiotic division.",
   "Primary spermatocytes divide by mitotic cell division.",
   "Spermatozoa are transformed into spermatids."], "B",
  "Secondary spermatocytes are haploid (23) and undergo meiosis II."),
 (70, "Choose the incorrect statement from the following: A. In birds and mammals, internal fertilisation takes place. B. Colostrum contains antibodies and nutrients. C. Polyspermy in mammals is prevented by the chemical changes in the egg nucleus. D. In the human female implantation occurs almost seven days after fertilisation.",
  ["D", "C", "B", "A"], "B",
  "Polyspermy is blocked by changes in the egg membrane/zona (cortical reaction), not the nucleus."),
 (71, "Select the option that shows the correctly identified U, X, Y and Z in a developing dicot embryo.",
  ["X - Cotyledon (2n), Y - Radicle (n), Z - Plumule (n), U - Suspensor (n).",
   "X - Suspensor (2n), Y - Cotyledon (2n), Z - Radicle (2n), U - Plumule (2n).",
   "X - Plumule (2n), Y - Suspensor (n), Z - Cotyledon (2n), U - Radicle (2n).",
   "X - Plumule (2n), Y - Suspensor (2n), Z - Radicle (2n), U - Cotyledon (2n)."], "B",
  "All embryonic parts are diploid; X is the suspensor near the micropyle."),
 (72, "Identify \"A\" and \"B\" in the T.S. of mature anther",
  ["Stomium and microspore mother cell", "Epidermis and tapetum",
   "Microspore mother cell and Tapetum", "Middle layer and Tapetum"], "B",
  "B is the outer epidermis and A the innermost tapetum layer."),
 (73, "Identify the part of Blastocyst labelled as \"A\"",
  ["Trophoblast", "Merula", "Epidermis", "Blastula"], "A",
  "The outer layer of the blastocyst is the trophoblast."),
 (74, "Spot the odd one out with reference to the male reproductive system:",
  ["Epididymis", "Vasa efferentia", "Isthmus", "Rete testis"], "C",
  "Isthmus is part of the female oviduct; the rest are male ducts."),
 (75, "Identify the odd one from the following:",
  ["Fimbriae", "Infundibulum", "Labia minora", "Isthmus"], "C",
  "Fimbriae, infundibulum and isthmus are parts of the oviduct; labia minora is external genitalia."),
]


async def run_bio_seed(db):
    admin = await db.users.find_one({"email": "admin@examnest.io"})
    admin_id = admin["id"] if admin else "system"
    now = _now()

    qids = []
    for (n, text, options, correct, expl) in QUESTIONS:
        qid = _qid(n)
        qids.append(qid)
        doc = {
            "id": qid, "type": "mcq_single", "subject": "Biology", "chapter": CHAPTER,
            "topic": "Human Reproduction / Reproduction in Flowering Plants",
            "difficulty": DIFFICULTY.get(n, "medium"), "marks": 4, "negative_marks": 1,
            "text": restore_table(n, text), "options": options, "correct": [correct], "explanation": expl,
            "hint": "", "language": "English",
            "image_url": IMAGES.get(str(n)), "source": SOURCE_TAG, "status": "approved",
            "exam": "CBSE", "student_class": "12", "year": "", "series": "", "tags": ["CBSE", "Class 12", "Biology"],
            "created_at": now, "created_by": admin_id,
        }
        await db.questions.replace_one({"id": qid}, doc, upsert=True)

    test_doc = {
        "id": TEST_ID,
        "title": "CBSE Class 12 Biology — Sexual Reproduction in Flowering Plants & Human Reproduction (75 MCQs)",
        "exam_type": "chapter_wise",
        "description": "75-question CBSE Class 12 Biology worksheet with diagram-based questions. NEET-style scoring: +4 for correct, −1 for wrong.",
        "subjects": ["Biology"], "duration_minutes": 75, "total_marks": float(len(QUESTIONS) * 4),
        "negative_marking": True, "shuffle_questions": False, "shuffle_options": False,
        "show_solutions_after": True, "question_ids": qids, "sections": [],
        "assigned_to": [], "created_by": admin_id, "created_by_role": "admin",
        "source": SOURCE_TAG, "created_at": now,
    }
    await db.tests.replace_one({"id": TEST_ID}, test_doc, upsert=True)
    return {"questions": len(qids), "test_id": TEST_ID, "images": len(IMAGES)}
